### ISSUE TITLE
unexpected output

### ISSUE THREAD

**Issue by audricd** [justlark/gempost#7]
hello,

With this gemini server (https://github.com/a-h/gemini):
```
name: geminicapsule
services:
    gemini:
        volumes:
            - /home/kireek/docker/gemini_capsule/certs:/certs
            - /home/kireek/docker/gemini_capsule/content:/content
        environment:
            - PORT=1965
            - DOMAIN=capsula.labaudric.net
        ports:
            - 1965:1965
        image: adrianhesketh/gemini:latest
```

and using gemlog (https://github.com/justlark/gempost)
![image](https://github.com/user-attachments/assets/c55ff4e7-7442-4bb9-ae98-876af9b4a189)

Going to the root of the website is showing me directory listing, as such:
![image](https://github.com/user-attachments/assets/3f3fd326-110d-4d9b-aa93-cfaed792fe62)

If in my docker compose I set the directory root to /static, rather than its parent, the links to /posts, /public, and /static will not work.

sorry this is most likely due to a stupid misconfiguration. this is my first gemini capsule attempt.

it happens with both lagrange, and krystall. desktop and mobile
